name: flutter_translation_sheet
description: Flutter Translation Sheet (fts) is a simple tool to help you with
  localization (l10n), using automatic GoogleSheet translations via Google
  Translate, generating json, arb and dart files.
version: 1.0.27
maintainer: Rodrigo LÃ³pez (@roipeker)
homepage: https://github.com/roipeker/flutter_translation_sheet
repository: https://github.com/roipeker/flutter_translation_sheet/
issue_tracker: https://github.com/roipeker/flutter_translation_sheet/issues

executables:
  fts: main

environment:
  sdk: ">=3.0.0 <3.1.0"

dependencies:
  args: ^2.4.1
  collection: ^1.17.2
  dcli: ^2.2.2
  googleapis: ^11.1.0
  googleapis_auth: ^1.4.0
  http: ^0.13.6
  io: ^1.0.4
  path: ^1.8.3
  recase: ^4.1.0
  watcher: ^1.1.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.1.0